config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :events do
    resources :attendances
    member do
      get :guests
    end
  end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  post "checkout", to: "checkout#create"
  get "payments/success", to: "payments#success", as: "payment_success"

  root "static_pages#home"
end

app/views/shared/_events_list.html.erb
<div>
  <% events.each do |event| %>
    <div class="card mb-4 shadow-sm">
        <div class="card-body">
            <h5 class="card-title text-dark"><%=event.title%></h5>
            <p class="card-text"><span class=" text-primary">Description:</span> <%= truncate(event.description, length: 20, separator: '...') %></p>
            <hr>
<br>
            <p class="text-muted mb-1">
           🧑 Evenement créé par <strong>
<% if event.user %>
  <%= event.user.fullname %>
<% else %>
  Inconnu
<% end %>
</strong>
              <br>
              🕒 date de l'evenement : <strong><%= french_date_format(event) %></strong>
              <br>
🏠 Lieu : <strong>
  <% if event.location.present? %>
    <%= event.location %>
  <% else %>
    TBC
  <% end %>
</strong>
<br>
<p><strong>Participants :</strong> <%= pluralize(event.attendances.count, "participant") %></p>
<br>
💰 Tarif : <strong><%= event.price %> €</strong>
<br>
⌛ Durée : <strong><%= min_to_hour(event.duration)  %></strong>
            </p>
            <%= link_to "Lire plus", event_path(event), class: "btn btn-outline-primary mt-2" %>
        </div>
    </div>
  <% end %>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
<% css_class = case type.to_sym
    when :notice then "alert alert-success"
    when :alert  then "alert alert-danger"
    else "alert alert-info"
  end %>

<div class="<%= css_class %>" role="alert">
    <%= message %>
</div>
<% end %>

app/views/shared/_form_event.html.erb
<%= form_with model: @event, local: true do |form| %>
    
    <div class="mb-3">
      <%= form.label :title, "Titre" %>
      <%= form.text_field :title, class: "form-control" %>
    </div>
    
    <div class="mb-3">
      <%= form.label :description, "Description" %>
      <%= form.text_area :description, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :location, "Lieu" %>
      <%= form.text_field :location, class: "form-control" %>
    </div>
<div class="mb-3">
  <%= form.label :start_date, "Date et heure de l'évènement" %>
  <%= form.datetime_local_field :start_date, class: "form-control", value: Time.current.change(min: 0) + 1.day %>
</div>



    <div class="mb-3">
      <%= form.label :price, "Tarif" %>
      <%= form.number_field :price, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :duration, "Durée" %>
      <%= form.number_field :duration, class: "form-control", placeholder: "Durée en minutes" %>
    </div>
     
    
    <%= form.submit @event.new_record? ? "Créer event" : "Modifier event", class: "btn btn-primary" %>
    
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav>
    <div class="wrapper_navbar">
        <ul class="mainMenu_navbar">
          <li class="item_navbar"><%= link_to "Accueil", root_path , class: "btn_navbar"%></li>
            <% if user_signed_in? %>
              <li class="item_navbar" id="account"><%= link_to "🧑 Mon profil", user_path(current_user), class: "btn_navbar" %>
              </li>
              <li class="item_navbar" id="all_events"><%= link_to "🗞️ Tous les evenements", events_path, class: "btn_navbar" %></li>
              <li class="item_navbar" id="my_events">
                <a href="#my_events" class="btn_navbar">📅 Mes évènements</a>
                <ul class="subMenu_navbar">
                  <% current_user.created_events.each do |event| %>
                    <li><%= link_to event.title, guests_event_path(event)%>
                    </li>
                  <% end %>
                </ul>
              </li>
              <li class="item_navbar"><%= button_to "Se déconnecter",destroy_user_session_path, 
            method: :delete, data: { confirm: "Es-tu sûr(e) ?" } , class: "btn_navbar"%></li>
            <% else %>
              <li class="item_navbar" id="connexion">
                <a href="#connexion" class="btn_navbar">Connexion</a>
                <ul class="subMenu_navbar">
              <li><%= link_to "Se connecter", new_user_session_path%></li>
              <li><%= link_to "S'inscrire", new_user_registration_path %></li>
                </ul>
            </li>
            <% end %>
        </ul>
    </div>
</nav>