config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :events do
    resources :attendances
    member do
      get :guests
    end
  end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  post "checkout", to: "checkout#create"
  get "payments/success", to: "payments#success", as: "payment_success"

  root "static_pages#home"
end

app/models/event.rb
  class Event < ApplicationRecord
    belongs_to :user
    has_many :attendances, dependent: :destroy
    has_many :users, through: :attendances

    validates :start_date, presence: true
    validate  :start_date_not_in_the_past

    validates :duration, presence: true, numericality: { only_integer: true, greater_than: 0 }
    validate  :duration_multiple5

    validates :title, presence: true, length: { in: 5..140 }
    validates :description, presence: true, length: { in: 20..1000 }
    validates :price, presence: true, inclusion: { in: 1..1000 }
    validates :location, presence: true

    private

    def start_date_not_in_the_past
      if start_date.present? && start_date < Time.current
        errors.add(:start_date, "date doit être dans le futur")
      end
    end

    def duration_multiple5
      if duration.present? && duration % 5 != 0
        errors.add(:duration, "la durée doit être un multiple de 5")
      end
    end
  end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [ :show, :edit, :update, :destroy, :guests ]

  before_action :authenticate_user!, only: [ :new, :create, :edit, :update, :destroy ]
  before_action :authorize_owner!, only: [ :edit, :update, :destroy, :guests ]

  def index
    @events = Event.includes(:user, :attendances).order(start_date: :desc)
  end

  def show
    if params[:success] == "true" && current_user
      Attendance.find_or_create_by(user: current_user, event: @event)
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)


    respond_to do |format|
      if @event.save
        format.html {
          flash[:notice] = "Événement créé !"
          redirect_to event_path(@event)
        }
        format.json { render :show, status: :created, location: @event }
      else
        format.html {
          flash.now[:alert] = "Échec de la création : #{@event.errors.full_messages.join(', ')}"

          render :new
        }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html {
          flash[:notice] = "Événement mis à jour !"
          redirect_to event_path(@event)
        }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html {
          flash.now[:alert] = "Échec de la mise à jour."
          render :edit
        }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html {
        flash[:notice] = "Événement supprimé !"
        redirect_to events_path
      }
      format.json { head :no_content }
    end
  end

  def guests
    @attendances = @event.attendances.includes(:user)
  end

  private

  def authorize_owner!
    unless @event.user == current_user
      redirect_to events_path, alert: "Tu n'es pas autorisé à accéder à cette page."
    end
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :description, :start_date, :duration, :price, :location)
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def french_date_format(event)
    I18n.l(event.start_date, format: :evenement)
  end

  def min_to_hour(minutes)
    minutes = minutes.to_i
       if minutes < 60
      "#{minutes} min"
       else
    hours = minutes / 60
    minutes_remain = minutes % 60
    formated_minutes = minutes_remain.to_s.rjust(2, "0")
    "#{hours}h#{formated_minutes}"
       end
  end

  def price_cents (price)
    price = price * 100
  end
end

app/views/events/edit.html.erb
<%= render 'shared/form_event', event: @event%>

app/views/events/guests.html.erb
<h2>Liste des invités pour <%= @event.title %></h2>

<table class="table">
  <thead>
    <tr>
      <th>Nom</th>
      <th>Email</th>
    </tr>
  </thead>
  <tbody>
    <% @attendances.each do |attendance| %>
      <tr>
        <td><%= attendance.user.fullname %></td>
        <td><%= attendance.user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="mt-3">
  <%= link_to 'Modifier l\'événement', edit_event_path(@event), class: "btn btn-primary" %>
  <%= link_to 'Supprimer l\'événement', event_path(@event), method: :delete, data: { confirm: "Êtes-vous sûr ?" }, class: "btn btn-danger" %>
  <%= link_to 'Retour aux événements', events_path, class: "btn btn-secondary" %>
</div>

app/views/events/index.html.erb
<div class="container my-5">

    <div class="d-flex justify-content-between mb-4" style="gap: 10px;">
        <h2 class="text-primary mb-4">Tous les Evenements 📃</h2>
<div><%= link_to "Créer un nouveau evenement", new_event_path, class: "btn btn-primary mt-2" %></div>
    </div>
    <div>
        <%= render partial: 'shared/events_list', locals: { events: @events } %>

    </div>
</div>

app/views/events/new.html.erb
<%= render 'shared/form_event', event: @event %>

app/views/events/show.html.erb
<div class="card mb-5 shadow-sm">
    <div class="row g-0">
        <div class="col-md-4 d-flex align-items-center justify-content-center p-4">
<%= image_tag 'default_avatar.png',
  alt: @event.user&.fullname || "Inconnu",
  class: "img-fluid rounded-circle border border-2 border-primary",
  style: "max-width: 150px;" %>



        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h2 class="card-title text-primary mb-3"><%= @event.title %></h2>
                <div class="speech-bubble bg-light p-4 mb-3">
                    <%= simple_format(@event.description) %>
                </div>
                <br>
                <p class="text-muted small mb-3">
                  🧑 Evènement ajouté Par 
<% if @event.user %>
  <%= link_to @event.user.fullname, user_path(@event.user), class: "fw-bold text-decoration-none" %>
<% else %>
  <strong>Inconnu</strong>
<% end %>
                  <br>
🏠 Lieu : <strong>
  <% if @event.location.present? %>
    <%= @event.location %>
  <% else %>
    TBC
  <% end %>
</strong>
<br>
<p>Nombre de participants : <%= @event.attendances.count %></p>


                  <br>
                  🕒 Date de l'évènement : <%= french_date_format(@event) %>
                  <br>
💰 Tarif : <%= @event.price %> €
<br>
⌛ Durée : <%= @event.duration %> minutes
                </p>
                  <% if current_user == @event.user %>
                  <div class="d-flex justify-content-start align-items-center mb-4" style="gap: 10px;">
                    <%= link_to "✏️ Modifier cet evenement", edit_event_path(@event), class: "btn btn-warning" %>
                    <%= button_to "🗑️ Supprimer", event_path(@event), method: :delete, data: { confirm: "Êtes-vous sûr de vouloir le supprimer  ?" }, class: "btn btn-danger" %>
                  </div>
                  <% else %>
                  <%= render partial: 'attendances/shared/form', locals: { event: @event, attendance: Attendance.new } %>
                <% end %>
            </div>
        </div>
    </div>
</div>
<div>
  <% if user_signed_in? %>
  <% if @event.users.include?(current_user) %>
    <p class="text-success">✅ Tu es déjà inscrit(e) à cet événement.</p>
  <% else %>
    <%= render 'attendances/shared/form', event: @event, attendance: Attendance.new %>
    <%= button_to "Acheter avec Stripe", checkout_path(event_id: @event.id), method: :post, data: { turbo: false } %>
  <% end %>
<% else %>
  <p class="text-danger">🔒 Connecte-toi pour pouvoir t'inscrire.</p>
  <%= link_to "Connexion", new_user_session_path, class: "btn btn-outline-primary" %>
<% end %>

</div>
<div class="d-flex justify-content-around align-items-center mb-4" style="gap: 10px;">
  <%= link_to "← Retour à la liste", events_path, class: "btn btn-outline-secondary" %>
  <%# <%= link_to "📝 Créer un nouveau event", new_event_path, class: "btn btn-primary " %> 
</div>